openapi: 3.0.0
info:
  title: Animal API
  version: 1.0.0
paths:
  /animal/{id}:
    get:
      summary: Get an animal by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single animal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animal'
        '404':
          description: Animal not found
components:
  schemas:
    Animal:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
        typeAnimal:
          type: string
        breed:
          type: string
        description:
          type: string
