openapi: 3.0.0
info:
  title: Donation API
  version: 1.0.0
paths:
  /donation:
    get:
      summary: Get all donations
      responses:
        '200':
          description: A list of donations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Donation'
    post:
      summary: Create a new donation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Donation'
      responses:
        '201':
          description: Donation created
  /donation/{id}:
    get:
      summary: Get a donation by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single donation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Donation'
        '404':
          description: Donation not found
    delete:
      summary: Delete a donation by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Donation deleted
        '404':
          description: Donation not found
    put:
      summary: Update a donation by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Donation'
      responses:
        '200':
          description: Donation updated
components:
  schemas:
    Donation:
      type: object
      properties:
        id:
          type: integer
        idPerson:
          type: integer
        type:
          type: string
        quantity:
          type: integer
